### ISSUE TITLE
内容是乱码。

### ISSUE THREAD

**Issue by iT0toro** [skywolf627/VmessActions#6]
导入文件后，不管是代理名字还是其他的显示的都是乱码。是不是保存文件的时候编码格式选错了。

**Comment by skywolf627** [comment]
又没啥影响，偶尔会乱码



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月3日(周二) 上午10:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [skywolf627/VmessActions] 内容是乱码。 (#6)




 
导入文件后，不管是代理名字还是其他的显示的都是乱码。是不是保存文件的时候编码格式选错了。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by anaer** [comment]
main.py加一行 可以处理乱码
clashTxt.encoding = "utf-8"
