### ISSUE TITLE
源更新报错(Android)

### ISSUE THREAD

**Issue by EdenLeaf** [skywolf627/VmessActions#8]
使用Clash for Android订阅国内镜像源的时候：
更新失败：rule[46][RULE-SET,private,DIRECT]error:unsupported rule type RULE-SET
几天前初次订阅的时候订阅成功了，但是无法更新订阅， 准备再另一个设备上订阅的时候也是同样的报错
在网上找好久的解决方法也找不到，只能过来提问了0.0
另外订阅原版源的时候提示
Get"https://raw.githubusercontent.com/skywolf627/VmessActions/main/subscribe/clash.yml":read tcp 192.168.3.102:43078->185.199.108.133:443:read:connection reset by peer
在CFW都能正常订阅和更新，为啥Clash for Android会出这个问题，求大佬提示一下0.0

**Comment by skywolf627** [comment]
你这个订阅的是github原版的，国内网络经常抽风导致无法访问。
要么是过段时间再访问，要么用镜像版，要么你先挂个梯子出去再拉



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月4日(周六) 下午3:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [skywolf627/VmessActions] 源更新报错(Android) (#8)




 
使用Clash for Android订阅国内镜像源的时候：
 更新失败：rule[46][RULE-SET,private,DIRECT]error:unsupported rule type RULE-SET
 几天前初次订阅的时候订阅成功了，但是无法更新订阅， 准备再另一个设备上订阅的时候也是同样的报错
 在网上找好久的解决方法也找不到，只能过来提问了0.0
 另外订阅原版源的时候提示
 Get"https://raw.githubusercontent.com/skywolf627/VmessActions/main/subscribe/clash.yml":read tcp 192.168.3.102:43078-&gt;185.199.108.133:443:read:connection reset by peer
 在CFW都能正常订阅和更新，为啥Clash for Android会出这个问题，求大佬提示一下0.0
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by EdenLeaf** [comment]
> 你这个订阅的是github原版的，国内网络经常抽风导致无法访问。 要么是过段时间再访问，要么用镜像版，要么你先挂个梯子出去再拉
> […](#)
我用镜像版是报   rule[46][RULE-SET,private,DIRECT]error:unsupported rule type RULE-SET   这个问题
github原版我挂梯子的时候拉也是这样
先不管原版吧，镜像版这个报错怎么办0.0

**Comment by skywolf627** [comment]
> > 你这个订阅的是github原版的，国内网络经常抽风导致无法访问。 要么是过段时间再访问，要么用镜像版，要么你先挂个梯子出去再拉
> > […](#)
> > 我用镜像版是报   rule[46][RULE-SET,private,DIRECT]error:unsupported rule type RULE-SET   这个问题
> > github原版我挂梯子的时候拉也是这样
> > 先不管原版吧，镜像版这个报错怎么办0.0

我这边两个订阅链接 拉取都没问题
可能是缓存吧，等过一天你再试试

**Comment by EdenLeaf** [comment]
> 我这边两个订阅链接 拉取都没问题
> 可能是缓存吧，等过一天你再试试
我这边用PC的话拉取也没问题，就是安卓端，不管是我原来的手机，还是从来没有用过的手机去拉取，都会报错，而且拉国内镜像源的报错都是  rule[46][RULE-SET,private,DIRECT]error:unsupported rule type RULE-SET ，并且我最初在手机端用的时候是能拉取的，大概是9.2

**Comment by skywolf627** [comment]
> > 我这边两个订阅链接 拉取都没问题
> > 可能是缓存吧，等过一天你再试试
> > 我这边用PC的话拉取也没问题，就是安卓端，不管是我原来的手机，还是从来没有用过的手机去拉取，都会报错，而且拉国内镜像源的报错都是  rule[46][RULE-SET,private,DIRECT]error:unsupported rule type RULE-SET ，并且我最初在手机端用的时候是能拉取的，大概是9.2

这就不晓得了 是不是你的 clash安卓版本的原因，不支持规则，下个最新版试试  我是2.4.9

**Comment by gtang8** [comment]
我用2.3.22Clash for Android,没有问题
